### ISSUE TITLE
微软手机端搜索积分一直为0

### ISSUE THREAD

**Issue by Alohaq** [geoi6sam1/FuckScripts#2]
大佬，请问pc上edge运行脚本猫，是不是连带手机端搜索任务也一起做了啊？可是为什么每次60分都为0呢

**Comment by geoi6sam1** [comment]
正常来说按顺序运行都能完成，还未遇到过你这种情况。脚本是先完成电脑搜索再完成移动设备搜索，避免同时搜索积分无法获取；建议重新登陆必应搜索试试。

**Comment by NeverSettle666** [comment]
我的也是

**Comment by Alohaq** [comment]
> 正常来说按顺序运行都能完成，还未遇到过你这种情况。脚本是先完成电脑搜索再完成移动设备搜索，避免同时搜索积分无法获取；建议重新登陆必应搜索试试。

我后来edge清了一次缓存 还是没用，然后我就转到chrome，神奇的来了，居然偶尔可行，然后edge的还是始终不可以

**Comment by Alohaq** [comment]
> 我的也是

如果是edge，换到chrome试试看？我这不有所改善，手机积分有概率能获取
