### ISSUE TITLE
微软积分商城的脚本这几天手机端任务开始有限制了

### ISSUE THREAD

**Issue by JaniQuiz** [geoi6sam1/FuckScripts#4]
之前一直正常运行，这几天手机端任务开始有限制了，只能完成部分。
电脑端任务还是正常运行
使用edge浏览器和chrome浏览器都有限制
手动完成App任务不受影响
![image](https://github.com/user-attachments/assets/ce78b77f-d802-466d-8a44-7d979d6789f3)

**Comment by JaniQuiz** [comment]
最开始使用的脚本猫上的1.1.4版本的，也是出过一次限制，后来换成github上的1.1.4.1版本后没有限制了，现在又出现限制了

**Comment by MuXin0123** [comment]
> 最开始使用的脚本猫上的1.1.4版本的，也是出过一次限制，后来换成github上的1.1.4.1版本后没有限制了，现在又出现限制了

我完全好像完全刷不了手机上的积分。一直被限制

**Comment by geoi6sam1** [comment]
> > 最开始使用的脚本猫上的1.1.4版本的，也是出过一次限制，后来换成github上的1.1.4.1版本后没有限制了，现在又出现限制了
> 
> 我完全好像完全刷不了手机上的积分。一直被限制

如果一直获取不到积分，需要把微软相关cookie全部清除，然后重新登录（.live.com、.bing.com、.microsoft.com）

**Comment by geoi6sam1** [comment]
> 最开始使用的脚本猫上的1.1.4版本的，也是出过一次限制，后来换成github上的1.1.4.1版本后没有限制了，现在又出现限制了

现在微软好像是直接限制了每15-20min只能获得4次搜索积分

**Comment by MuXin0123** [comment]
> > 最开始使用的脚本猫上的1.1.4版本的，也是出过一次限制，后来换成github上的1.1.4.1版本后没有限制了，现在又出现限制了
> 
> 现在微软好像是直接限制了每15-20min只能获得4次搜索积分

我用了两天又可以全部完成了。。挺神奇的。
