### ISSUE TITLE
版本 2.1.0，好象不做 每日活动

### ISSUE THREAD

**Issue by testonlys** [geoi6sam1/FuckScripts#6]
版本 2.1.0，好象不做 每日活动；另外我的帐号 dashboard.userStatus 中没有 mobileSearch ，读书活动好象也没有，是不是要下载APP登录一次？

**Comment by geoi6sam1** [comment]
官方限制了活动和阅读要中午12点后才能完成，新注册的账号1级是没有移动设备搜索的

**Comment by Gao-sy** [comment]
脚本安装完每小时会自动执行吗，有什么提示吗，我这里看的好像没啥反应

**Comment by Gao-sy** [comment]
安装错位置了，安装到篡改猴了，脚本猫试了下，可以正常运行了

**Comment by testonlys** [comment]
> 官方限制了活动和阅读要中午12点后才能完成，新注册的账号1级是没有移动设备搜索的

不清楚有这限制，麻烦关闭了吧，谢谢
